### ISSUE TITLE
Gants de Manutention

### ISSUE THREAD

**Issue by FloRide1** [Atelier-Epita/fiches-machines#1]
Yo les gars, juste une petite remarque: Pour certains objets tournants (perceuse a colonne, etc...) le port des gants c'est considéré comme un danger (a cause du risque d'entrainement de la main), donc peux etre le rendre "interdit" plutot que "obligatoire" 

Une petite photo de la notre au cas ou ;) :
![IMG_20220511_085558](https://user-images.githubusercontent.com/43076999/167787963-d1763c62-7c4f-42c6-9dc8-7b4c6c806670.jpg)

**Comment by jubbakka** [comment]
c'est fix
